### ISSUE TITLE
rework block rendering

### ISSUE THREAD

**Issue by CodeCrafter47** [nicosio2/MineFluence#6]
use new json stuff

benefits:
- easier to understand (for me)
- easier to mod for texture pack makers
- fixes a crash when running the mod only on a server
- fixes inconsistent look of placed blocks versus blocks in inventory
- requires less textures per block
- block break animation can be added without knowing about opengl stuff

**Comment by CodeCrafter47** [comment]
The json models are now updated to look same as the model in the tileentity renderer.

The tile entity renderer is still in effect for rendering placed blocks. Using the json models for this is difficult as long as the different machine blocks are just metadata based subblocks. Being effectively the same block requires all machine blocks to have the same properties, but in effect they have quite different properties. For example the display block can be aligned to multiple directions and also has the progress properties, while the needs neither of these properties. A future thermometer might need a heat property. To be clear this is just about the properties which are important to the client.

For this reason I would suggest to create a separate block for each machine block. Any thoughts?

**Comment by CherryWorm** [comment]
Yeah, that propably wouldnt be that hard and it will make the code more readable as well.

**Comment by CodeCrafter47** [comment]
Done.
